=== manuelcespedesrguez-ux/Marcas/XML/empleados.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

        <!-- Definición de elementos finales -->
            <xs:element name="NOMBRE"   type="xs:string" />
            <xs:element name="APELLIDO" type="xs:string" />
            <xs:element name="EDAD"     type="xs:integer" />
            <xs:element name="DEPARTAMENTO" type="xs:string" />
            <xs:element name="CARGO"    type="xs:string" />
       
        <!-- Elemento complejo empleado -->
            <xs:element name="EMPLEADO">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element ref="NOMBRE" />
                        <xs:element ref="APELLIDO" />
                        <xs:element ref="EDAD" />
                        <xs:element ref="DEPARTAMENTO" />
                        <xs:element ref="CARGO" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

        <!-- Elemento raíz Empleados-->
            <xs:element name="EMPLEADOS">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element ref="EMPLEADO" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
</xs:schema>

=== manuelcespedesrguez-ux/Marcas/XML/empleados.xml
<?xml version="1.0" encoding="UTF-8"?>
<EMPLEADOS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="empleados.xsd">

        <EMPLEADO>
            <NOMBRE>Ana</NOMBRE>
            <APELLIDO>García</APELLIDO>
            <EDAD>30</EDAD>
            <DEPARTAMENTO>Ventas</DEPARTAMENTO>
            <CARGO>Ejecutivo de ventas</CARGO>
        </EMPLEADO>
        <EMPLEADO>
            <NOMBRE>Luis</NOMBRE>
            <APELLIDO>Rodríguez</APELLIDO>
            <EDAD>45</EDAD>
            <DEPARTAMENTO>Finanzas</DEPARTAMENTO>
            <CARGO>Analista de financiero</CARGO>
        </EMPLEADO>
        <EMPLEADO>
            <NOMBRE>María</NOMBRE>
            <APELLIDO>López</APELLIDO>
            <EDAD>28</EDAD>
            <DEPARTAMENTO>Marketing</DEPARTAMENTO>
            <CARGO>Especialista en redes sociales</CARGO>
        </EMPLEADO>

</EMPLEADOS>
